name: Run tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.12.0

            - name: Setup PNPM
              uses: pnpm/action-setup@v3
              with:
                  version: 9.0.0
                  run_install: false

            - name: Resolve PNPM store path
              id: pnpm-store-path
              run: |
                  echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Setup PNPM cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-store-path.outputs.PNPM_STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run test
              run: pnpm test:once
